
ALTER TABLE terminals DROP CONSTRAINT IF EXISTS terminal_shop_fk CASCADE;
ALTER TABLE shops DROP CONSTRAINT IF EXISTS shops_merchant_fk CASCADE;
ALTER TABLE merchants DROP CONSTRAINT IF EXISTS merchants_partner_fk CASCADE;

DROP TABLE IF EXISTS terminals CASCADE;
DROP TABLE IF EXISTS shops CASCADE;
DROP TABLE IF EXISTS merchants CASCADE;
DROP TABLE IF EXISTS partners CASCADE;
DROP TYPE role;