// Code generated by sqlc. DO NOT EDIT.

package merchant

import (
	"context"

	"github.com/jackc/pgtype"
)

type Querier interface {
	AddMerchant(ctx context.Context, arg AddMerchantParams) (Merchant, error)
	AddPartner(ctx context.Context, arg AddPartnerParams) (Partner, error)
	DeleteMerchant(ctx context.Context, id pgtype.UUID) (Merchant, error)
	DeletePartner(ctx context.Context, id pgtype.UUID) (Partner, error)
}

var _ Querier = (*Queries)(nil)
