build-prod-image:
  extends:
    - .prod
    - .build_image

# Deploy
deploy-prod-sha:
  only:
    changes:
      - "*"
      - "**/*"
  extends:
    - .deploy-prod
    - .deploy-sha

# deploy-prod-api-bo-latest:
#   except:
#     changes:
#       - "app/*"
#       - "app/**/*"
#   extends:
#     - .deploy-prod
#     - .deploy-latest
